import { DM_Sans, Poppins } from "next/font/google";
import "./globals.css";

const font = Poppins({
  subsets: ["latin"],
  weight:['400','500'],
  style:['normal','italic'],
  variable:"--font-serif",
});

const dmsans = DM_Sans({
  subsets: ["latin"],
  weight:['400','500'],
  style:['normal','italic'],
  variable:"--font-sans",
});





export const metadata = {
  title: "pixelflow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${font.variable} ${dmsans.variable} font-serif`}>
        {children}
      </body>
    </html>
  );
}
